server.port=8084
spring.application.name=fare-service

spring.data.mongodb.uri=${MONGO_URI:${MONGODB_URI:mongodb://127.0.0.1:27017/ridelink_fare_db}}
spring.data.mongodb.database=ridelink_fare_db
spring.data.mongodb.auto-index-creation=true

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss

logging.level.root=INFO
logging.level.com.example.fare_service=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
