name: RideLink Microservices CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

<<<<<<< HEAD
=======
    # Services 4 වෙන වෙනම parallel run කරන්න matrix එකක් පාවිච්චි කරනවා
>>>>>>> main
    strategy:
      fail-fast: false
      matrix:
        service:
          - account-service
          - driver-service
          - ride-service
          - fare-service

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MONGODB_URI: mongodb://127.0.0.1:27017/ride_service_test

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      - name: Build and Test ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: mvn clean test
